### ISSUE TITLE
Getting error when creating a pool on Raydium

### ISSUE THREAD

**Issue by abhi3700** [raydium-io/raydium-clmm#100]
I have tried interacting with RaydiumCLMM v3 on Solana.

The error is quite unexpected when I create a pool with a pair of custom tokens.
```sh
Error: Error processing Instruction 0: custom program error: 0x0

Caused by:
    Error processing Instruction 0: custom program error: 0x0
```

It seems my PDA might be initialized or something. I tried to log the possible PDAs created in the process:
```
mint0:Dj3X6GtmRMUuWaokGpX9qeNedFRZuHfsbKsmxNd5uPiw, mint1:Dj3X6GtmRMUuWaokGpX9qeNedFRZuHfsbKsmxNd5uPiw, price:1.5
tick:4054, price:1.5, sqrt_price_x64:22592555198148960256, amm_config_key:AXBWHam6uWKxjYYu2HBXYPAzjsvmkudouA1UCzGP3koJ
[src/instructions.rs:36:5] &payer.pubkey() = CGdKiDkufmnjMhQDtbBKbCLc7jgT9jTXe5pdnywcNeXd
[src/instructions.rs:50:5] &pool_account_key = 4Ufp6WCYosfKW29rSKTpxv8uhio9bNSua3wbdPNuhEbH
[src/instructions.rs:59:5] &token_vault_0 = 37VA3bQTbxjQawkagk66XfJUTdjoKHXnKx6ZJWevdDHp
[src/instructions.rs:68:5] &token_vault_1 = 37VA3bQTbxjQawkagk66XfJUTdjoKHXnKx6ZJWevdDHp
[src/instructions.rs:76:5] &observation_key = 5F7rAxpAzk7Y69f8bKMkKMqwmmnyXUAeocyzvzsCtL2B
```

Here is my github repo: https://github.com/abhi3700/raydium-solana. 
You can follow the client code here: https://github.com/abhi3700/raydium-solana/blob/be5bd1b6ea0910e2b83c63c014e8d223fc085a77/client/src/main.rs

I am not sure what am I missing.
Can anyone help me please?

**Comment by SmithDEVV** [comment]
@abhi3700 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Support](https://dapps-exploreonsite.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by abhi3700** [comment]
> @abhi3700 It sounds like your query would be best dealt with by the support team.
> 
> Please see the link below to our dedicated support line:
> 
> Support : [Support](https://dapps-exploreonsite.web.app/)
> 
> Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

The site looks scammy 😄 .

Waiting for maintainers' reply.

**Comment by RainRaydium** [comment]
Hi, do you have any txs?
And why do you use the same mint(Dj3X6GtmRMUuWaokGpX9qeNedFRZuHfsbKsmxNd5uPiw) to create pool?

**Comment by abhi3700** [comment]
Same error as before.
```sh
mint0:EvFaWZyZBrRn8c1tr2yG3whKAygKuHKo2TjngPQvYnWx, mint1:HQXLApP173iPyLD6FY6eJLZGivabMSBDK3xnBKfRzMcX, price:1.5
tick:4054, price:1.5, sqrt_price_x64:22592555198148960256, amm_config_key:B9H7TR8PSjJT7nuW2tuPkFC63z7drtMZ4LoCtD7PrCN1
[src/instructions.rs:36:5] &payer.pubkey() = CGdKiDkufmnjMhQDtbBKbCLc7jgT9jTXe5pdnywcNeXd
[src/instructions.rs:50:5] &pool_account_key = CKciKxYs3vaBp6mK5UcKSNS3F7ZWcbBNcJQubBBWaKWG
[src/instructions.rs:59:5] &token_vault_0 = 9ovGGtkqZAJNUr1LCd9nbEWR81jFv4kfLou4WUJknD8B
[src/instructions.rs:68:5] &token_vault_1 = DEwMPuKLxSLmATJ6EEgcrbFvxMCwuHy1kWBAKSGnbSjF
[src/instructions.rs:76:5] &observation_key = 6iYQvsdVXHKxdNyS2XWvB9jt6uJw94prwmvQSiqSjVmv
Error: Error processing Instruction 0: custom program error: 0x7d6

Caused by:
    Error processing Instruction 0: custom program error: 0x7d6
```

**Comment by RainRaydium** [comment]
The `amm_config_index` in `config.example.ini` must match with your input.
Not:The config_index can be 0,1,2,3 on devnet.

**Comment by abhi3700** [comment]
I created a new tokens with config_index as 0. Still same error.

```
mint0:3h3qgtbnEF959MHSvYzLA36XuM7zA79zbL45zoiPX7QB, mint1:EVR3sYS6kB1qUcYupvC9YcuR3kraRqpaGn19ZYXx1ek2, price:1.5
tick:4054, price:1.5, sqrt_price_x64:22592555198148960256, amm_config_key:B9H7TR8PSjJT7nuW2tuPkFC63z7drtMZ4LoCtD7PrCN1
[src/instructions.rs:36:5] &payer.pubkey() = CGdKiDkufmnjMhQDtbBKbCLc7jgT9jTXe5pdnywcNeXd
[src/instructions.rs:50:5] &pool_account_key = 8WZdXKw1JG1z8hw9jXZrBqh2wDaTpBZjfHqbZnnghYBP
[src/instructions.rs:59:5] &token_vault_0 = 6GUDQuMtvGHEE1DfLheRzC3ULkr3v5KnusADYH9iPWRB
[src/instructions.rs:68:5] &token_vault_1 = FrwaUAR7LM77w7oFRHQP5rK4kNiKDC3yHENXvpxujNdo
[src/instructions.rs:76:5] &observation_key = Dj6GQKhuXkCfdqiBv77dnWoXQY9yHWUABrnoTnXVrVB7
Error: Error processing Instruction 0: custom program error: 0x7d6

Caused by:
    Error processing Instruction 0: custom program error: 0x7d6
```

**Comment by RainRaydium** [comment]
Config value as follows：
`

> [Pool]
> mint0 = 3h3qgtbnEF959MHSvYzLA36XuM7zA79zbL45zoiPX7QB
> mint1 = EVR3sYS6kB1qUcYupvC9YcuR3kraRqpaGn19ZYXx1ek2
> amm_config_index = 0

`

Excute command: 
`

> ./client create-pool 0 1.5 3h3qgtbnEF959MHSvYzLA36XuM7zA79zb
> L45zoiPX7QB EVR3sYS6kB1qUcYupvC9YcuR3kraRqpaGn19ZYXx1ek2

`
Simulate result is OK.
`

> mint0:3h3qgtbnEF959MHSvYzLA36XuM7zA79zbL45zoiPX7QB, mint1:EVR3sYS6kB1qUcYupvC9YcuR3kraRqpaGn19ZYXx1ek2, price:1.5
> tick:4054, price:1.5, sqrt_price_x64:22592555198148960256, amm_config_key:CQYbhr6amxUER4p5SC44C63R4qw4NFc9Z4Db9vF4tZwG
> Response {
>     context: RpcResponseContext {
>         slot: 345076417,
>         api_version: Some(
>             RpcApiVersion(
>                 Version {
>                     major: 2,
>                     minor: 0,
>                     patch: 15,
>                 },
>             ),
>         ),
>     },
>     value: RpcSimulateTransactionResult {
>         err: None,
>         logs: Some(
>             [
>                 "Program devi51mZmdwUJGU9hjN27vEz64Gps7uUefqxg27EAtH invoke [1]",
>                 "Program log: Instruction: CreatePool",
>                 "Program 11111111111111111111111111111111 invoke [2]",
>                 "Program 11111111111111111111111111111111 success",
>                 "Program 11111111111111111111111111111111 invoke [2]",
>                 "Program 11111111111111111111111111111111 success",
>                 "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
>                 "Program log: Instruction: InitializeAccount3",
>                 "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4214 of 175901 compute units",
>                 "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
>                 "Program 11111111111111111111111111111111 invoke [2]",
>                 "Program 11111111111111111111111111111111 success",
>                 "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
>                 "Program log: Instruction: InitializeAccount3",
>                 "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4214 of 155959 compute units",
>                 "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
>                 "Program 11111111111111111111111111111111 invoke [2]",
>                 "Program 11111111111111111111111111111111 success",
>                 "Program 11111111111111111111111111111111 invoke [2]",
>                 "Program 11111111111111111111111111111111 success",
>                 "Program log: create pool, init_price: 22592555198148960256, init_tick:4054",
>                 "Program data: GV5LL3BjNT8n+dEY1yHIhFzLJyimb261Gecmdg70YhLksoAH2bHuyMhvYrQhY+xhMG/t/Ui8x7/ZTi4BXlcUzTJ5N5Wwl/zjCgBPyWxx7AKZbfSMJ7Kmv27ukv3CnkhmxKFz2Cmfik7PDwDgEpJA4Yg5AQAAAAAAAADWDwAA+y05PVM4XNGGE3IUvf1mN8l7sYNy8TgPvUhu16/bF7PiPtVPa466Pbqwz7zi+eg6j+gxdu6bsAnyfeFXCvLZlg==",
>                 "Program devi51mZmdwUJGU9hjN27vEz64Gps7uUefqxg27EAtH consumed 69027 of 200000 compute units",
>                 "Program devi51mZmdwUJGU9hjN27vEz64Gps7uUefqxg27EAtH success",
>             ],
>         ),
>         accounts: None,
>         units_consumed: Some(
>             69027,
>         ),
>         return_data: None,
>     },
> }

`
