### ISSUE TITLE
How do handle minimize large stack variables

### ISSUE THREAD

**Issue by hunghkit** [raydium-io/raydium-clmm#76]
Hello there, I'm newbie with Rust and researching Raydium Program, I'm getting some errors with Error: Function _ZN173_$LT$raydium_amm_v3..instructions..open_position..OpenPositionV2$u20$as$u20$anchor_lang..Accounts$LT$raydium_amm_v3..instructions..open_position..OpenPositionV2Bumps$GT$$GT$12try_accounts17hd80ee50634db5fd5E Stack offset of 5056 exceeded max offset of 4096 by 960 bytes, please minimize large stack variables when run "anchor build". I'm not sure how to setup or run it

Thank all!!!!

**Comment by RainRaydium** [comment]
What's the version of solana & anchor you dependence.
Please use anchor-cli 0.29.0 and solana version less than 1.18!
