### ISSUE TITLE
Clmm and Amm IDL mismatch.

### ISSUE THREAD

**Issue by vikito755** [raydium-io/raydium-clmm#87]
I built the "clmm" contract with "anchor build" after adding the appropriate "idl-build" features as instructed by the errors.

The resulting IDL a
ppears to be for the "Amm" contract, instead for the "Clmm" one.

Here is the resulting IDL
[amm_v3.json](https://github.com/user-attachments/files/16637404/amm_v3.json)

Is that an expected behaviour or have I made a mistake when building?

**Comment by RainRaydium** [comment]
That is correct, there is no problem, usually you only need to execute the `anchor build` command in the project directory.
